# fly.toml file generated for qc-server on 2022-12-30T21:48:08+05:30

app = "qc-server"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8100"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8100
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "2s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
